version: "3.5"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/src/go/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    environment:
      - APP_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=local-group
      - KAFKA_TOPIC=retain-offset
    working_dir: /src/go/app
    command: reflex -r '(\.go$$)' -s go run .
    depends_on:
      - kafka
      
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    environment: 
      KAFKA_LOG_RETENTION_MS: 10000
    ports:
      - "2181:2181"
    logging:
      driver: none

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: retain-offset:1:1
    depends_on:
      - zookeeper
    logging:
      driver: none
